### ISSUE TITLE
[Bug] Admin session gets logged out when trying to automatically connect to a BTCPay Instance to NopCommerce `https:/xxxAdmin/PaymentBTCPayServer/GetAutomaticApiKeyConfig?ssid=1`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/nopcommerce#1]
Having absoluetly the same problem when trying to automatically pair NopCommerce as here https://github.com/btcpayserver/grandnode/issues/2

**Comment by pavlenex** [comment]
Seems that this is the issue with logged out session.
<img width="1432" alt="Screenshot 2024-02-25 at 22 10 20" src="https://github.com/btcpayserver/nopcommerce/assets/36959754/6d254fa4-efce-4247-bc98-914a933ce228">

**Comment by ndeet** [comment]
this one is a bit different, it says "method not allowed" which could be that no POST requests are allowed, also I see images are broken on nopCommerce demo, will check and do some testing and report back

**Comment by pavlenex** [comment]
I believe this one was resolved in the latest release @ndeet @Nisaba ?

I think only thing remaining is to do one last test, then push that code and make a release according to #5  and we can then close the issues.
