### ISSUE TITLE
Unable to check out `Blocked loading mixed active content "checkout/OpcSaveBilling/"`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/nopcommerce#2]
Upon manually connecting the NopCommerce plugin, since automatic connection doesn't work #1, I am unable to proceed checking out. I've manage to track a bit what may be a problem, but you can attempt to do it yourself as well.

To replicate, simply go to our demo https://nopcommerce.demo.btcpay.tech/cart/ and try to check out.

```
Source map error: Error: request failed with status 404
Resource URL: https://nopcommerce.demo.btcpay.tech/js/dhvv7bnzqtwseiyivytzvq.scripts.js?v=Otry5Jimn9Yl4E6GekNhOc5wHNM
Source Map URL: jquery-migrate.min.map

Navigated to http://nopcommerce.demo.btcpay.tech/cart/
Blocked loading mixed active content "http://nopcommerce.demo.btcpay.tech/checkout/OpcSaveBilling/"
[dhvv7bnzqtwseiyivytzvq.scripts.js:2:82714](https://nopcommerce.demo.btcpay.tech/js/dhvv7bnzqtwseiyivytzvq.scripts.js?v=Otry5Jimn9Yl4E6GekNhOc5wHNM)
XHRPOST
http://nopcommerce.demo.btcpay.tech/checkout/OpcSaveBilling/
Mixed Block

GET
http://nopcommerce.demo.btcpay.tech/cart/
[HTTP/1.1 301 Moved Permanently 603ms]
```
<img width="1437" alt="Screenshot 2024-02-25 at 21 47 31" src="https://github.com/btcpayserver/nopcommerce/assets/36959754/4589f6b3-50a4-42f7-a34f-21b739b7b256">
<img width="1440" alt="Screenshot 2024-02-25 at 21 48 31" src="https://github.com/btcpayserver/nopcommerce/assets/36959754/2fbb4301-b996-46d5-829e-50a54d3e218f">

It seems it could be SSL related https://www.nopcommerce.com/en/boards/topic/89707/problem-with-ssl

https://www.nopcommerce.com/en/boards/topic/89707/problem-with-ssl

**Comment by ndeet** [comment]
Will check

**Comment by pavlenex** [comment]
This issue has been resolved, @ndeet can you post in PR in readme refferencing how this was fixed if someone encounters it or is it something plugin related?

**Comment by ndeet** [comment]
Seems to be fixed now, for anybody finding this the setup with nginx and linux is not obvious, after you have SSL enabled an it generally works but the checkout does not:

enable proxy support on hosting settings like described here:
https://github.com/nopSolutions/nopCommerce/issues/7051#issuecomment-1917756668

which will lead to an infinite loop ERR_TOO_MANY_REDIRECTS

you addtionally need to enable ssl on the store which is not possible in the UI for nopCommerce 4.60 for some reason
do a mysql query like `UPDATE nopcommerce.Store SET SslEnabled=1;`

**Comment by pavlenex** [comment]
Awesome it works now @ndeet should I add something to readme or, if yes can you suggest how to frame this and where to put it?
