### ISSUE TITLE
Additional fee in plugin configuration UI 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/nopcommerce#3]
Is there a good reason why we have `additional fee options` in the UI? This can be done on BTCPay's end, I feel like it's adding additional level of confusion, @Nisaba any good reasoning for this?

If no strong reasoning, we should probably remove it to avoid confusion and even possible review problems as it may look like a commercial plugin.

<img width="1349" alt="Screenshot 2024-02-25 at 22 25 06" src="https://github.com/btcpayserver/nopcommerce/assets/36959754/e7201472-326e-43b7-92d5-c2d4cc121927">

**Comment by Nisaba** [comment]
@pavlenex It's a standard feature for all payment plugins.
Nothing to do with free / commercial plugin since it is the end user who decides whether to apply fees or not

**Comment by pavlenex** [comment]
I am not really sure we do this in any other integration. I understand what this option  does, but I am worried it adds distraction in the configuration UI, when it can already be set up in the BTCPay backoffice anyway, and is highly advanced option. I am not questioning it's usefulness for some people, but I don't think majority of users would use it, wdyt @ndeet ?

**Comment by ndeet** [comment]
It seems to be a nopCommerce thing that shows up on every payment plugin configuration, so I think the merchants are used to it and we just leave it there. Some other ecommerce systems have that too. I would keep it as nopCommerce merchants are used to it anyway.
