### ISSUE TITLE
Update instructions in the UI or remove them and link to them?

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/nopcommerce#4]
It seems a bit intimidating when a new user is greeted with a wall and wall of text (that atm is a bit inaccurate).

Question I have is should we:
1. Edit the text and shorten it
2. Remove it and just link to readme for setup instructions?
3. Enhance tooltips?
<img width="1033" alt="Screenshot 2024-02-25 at 22 29 12" src="https://github.com/btcpayserver/nopcommerce/assets/36959754/43aa17dc-9c72-4669-a8c6-68c7e372ef61">

Wdyt @Nisaba @ndeet (This same question applies for GrandNode)?

Imo combination of 2) and 3) should be the most opimal.

**Comment by ndeet** [comment]
Maybe keep the automatic configuration and link to the manual configuration to keep it shorter as the description of api key generation and webhook is too distracting?

**Comment by Nisaba** [comment]
It seems that the 422 error paragraph is no longer relevant.
Since this case has been handled in the webhook for some time now...

**Comment by pavlenex** [comment]
Alright, I can take care of this one.
