### ISSUE TITLE
Should we have plugin releases (versions)

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/nopcommerce#5]
Should we start having releases to ensure specific versions of the plugins are released? Unsure how that goes with Nopcommerce marketplace, we should double-check wrt versioning.

**Comment by Nisaba** [comment]
Yes, 
the structure of the zip file must correspond to that expected by NopCommerce when importing the plugin

**Comment by pavlenex** [comment]
Would you be able to tackle that once we resolve the bugs we currently have, it doesn't make sense to release until we iron things out, do you agree?
